# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Damon Black
email: black.damon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my new home base on the internet. I hope to discuss the
  craft of web development and have a little fun in the process.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://damonblack.com" # the base hostname & protocol for your site
github_username:  damonblack

# Build settings
markdown: kramdown
