title: Damon Black
email: black.damon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "It is easier to fool people than to convince them they've been fooled" -- Mark Twain
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://damonblack.com" # the base hostname & protocol for your site
github_username:  damonblack

markdown: kramdown
